/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class megaclass */

#ifndef _Included_megaclass
#define _Included_megaclass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     megaclass
 * Method:    printOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_megaclass_printOne
  (JNIEnv *, jclass);

/*
 * Class:     megaclass
 * Method:    printTwo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_megaclass_printTwo
  (JNIEnv *, jclass);

/*
 * Class:     megaclass
 * Method:    Addition
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_megaclass_Addition
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     megaclass
 * Method:    Multiplication
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_megaclass_Multiplication
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
